version: "2"
services:
  web:
    image:  ssjt/jfinalcms:lfi
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    volumes:
      - ./pom.xml:/app/pom.xml
      - ./settings.xml:/usr/share/maven/conf/settings.xml
    networks:
      - vuln-network
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cms
      - TZ=Asia/Shanghai
    volumes:
      - ./initdb/:/docker-entrypoint-initdb.d/
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - vuln-network
networks:
  vuln-network:
    external: true