version: "2"
services:
  web:
    image:  ssjt/jfinalcms:lfi
    depends_on:
      - mysql
    ports:
      - "8000:8000"
#    volumes:
#      - ./classroombookings-2.6.4/:/var/www/html
    networks:
      - vuln-network
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cms
      - TZ=Asia/Shanghai
    volumes:
      - ./JFinaCMS.sql:/docker-entrypoint-initdb.d/JFinaCMS.sql
    ports:
      - 3306:3306
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - vuln-network
networks:
  vuln-network:
    external: true