package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContent<M extends BaseContent<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}
	
	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return getDate("createDate");
	}
	
	public M setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return getDate("updateDate");
	}
	
	public M setPublishDate(java.util.Date publishDate) {
		set("publishDate", publishDate);
		return (M)this;
	}
	
	public java.util.Date getPublishDate() {
		return getDate("publishDate");
	}
	
	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public Integer getStatus() {
		return getInt("status");
	}
	
	public M setAuthor(String author) {
		set("author", author);
		return (M)this;
	}
	
	public String getAuthor() {
		return getStr("author");
	}
	
	public M setSource(String source) {
		set("source", source);
		return (M)this;
	}
	
	public String getSource() {
		return getStr("source");
	}
	
	public M setOutlink(String outlink) {
		set("outlink", outlink);
		return (M)this;
	}
	
	public String getOutlink() {
		return getStr("outlink");
	}
	
	public M setIco(String ico) {
		set("ico", ico);
		return (M)this;
	}
	
	public String getIco() {
		return getStr("ico");
	}
	
	public M setImage(String image) {
		set("image", image);
		return (M)this;
	}
	
	public String getImage() {
		return getStr("image");
	}
	
	public M setPicValue(String picValue) {
		set("picValue", picValue);
		return (M)this;
	}
	
	public String getPicValue() {
		return getStr("picValue");
	}
	
	public M setTagIdValue(String tagIdValue) {
		set("tagIdValue", tagIdValue);
		return (M)this;
	}
	
	public String getTagIdValue() {
		return getStr("tagIdValue");
	}
	
	public M setAttach(String attach) {
		set("attach", attach);
		return (M)this;
	}
	
	public String getAttach() {
		return getStr("attach");
	}
	
	public M setIsTop(Boolean isTop) {
		set("isTop", isTop);
		return (M)this;
	}
	
	public Boolean getIsTop() {
		return get("isTop");
	}
	
	public M setIsRecommend(Boolean isRecommend) {
		set("isRecommend", isRecommend);
		return (M)this;
	}
	
	public Boolean getIsRecommend() {
		return get("isRecommend");
	}
	
	public M setIsHeadline(Boolean isHeadline) {
		set("isHeadline", isHeadline);
		return (M)this;
	}
	
	public Boolean getIsHeadline() {
		return get("isHeadline");
	}
	
	public M setVisits(Integer visits) {
		set("visits", visits);
		return (M)this;
	}
	
	public Integer getVisits() {
		return getInt("visits");
	}
	
	public M setLikes(Integer likes) {
		set("likes", likes);
		return (M)this;
	}
	
	public Integer getLikes() {
		return getInt("likes");
	}
	
	public M setOppose(Integer oppose) {
		set("oppose", oppose);
		return (M)this;
	}
	
	public Integer getOppose() {
		return getInt("oppose");
	}
	
	public M setSort(Integer sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public Integer getSort() {
		return getInt("sort");
	}
	
	public M setDescription(String description) {
		set("description", description);
		return (M)this;
	}
	
	public String getDescription() {
		return getStr("description");
	}
	
	public M setKeywords(String keywords) {
		set("keywords", keywords);
		return (M)this;
	}
	
	public String getKeywords() {
		return getStr("keywords");
	}
	
	public M setTitle(String title) {
		set("title", title);
		return (M)this;
	}
	
	public String getTitle() {
		return getStr("title");
	}
	
	public M setSubtitle(String subtitle) {
		set("subtitle", subtitle);
		return (M)this;
	}
	
	public String getSubtitle() {
		return getStr("subtitle");
	}
	
	public M setTitlecolor(String titlecolor) {
		set("titlecolor", titlecolor);
		return (M)this;
	}
	
	public String getTitlecolor() {
		return getStr("titlecolor");
	}
	
	public M setIntroduction(String introduction) {
		set("introduction", introduction);
		return (M)this;
	}
	
	public String getIntroduction() {
		return getStr("introduction");
	}
	
	public M setCategoryId(Integer categoryId) {
		set("categoryId", categoryId);
		return (M)this;
	}
	
	public Integer getCategoryId() {
		return getInt("categoryId");
	}
	
	public M setChunkValue(String chunkValue) {
		set("chunkValue", chunkValue);
		return (M)this;
	}
	
	public String getChunkValue() {
		return getStr("chunkValue");
	}
	
	public M setModelFieldValue(String modelFieldValue) {
		set("modelFieldValue", modelFieldValue);
		return (M)this;
	}
	
	public String getModelFieldValue() {
		return getStr("modelFieldValue");
	}
	
	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}
	
	public M setSiteId(Integer siteId) {
		set("siteId", siteId);
		return (M)this;
	}
	
	public Integer getSiteId() {
		return getInt("siteId");
	}
	
}

