package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWeb<M extends BaseWeb<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}
	
	public M setDomain(String domain) {
		set("domain", domain);
		return (M)this;
	}
	
	public String getDomain() {
		return getStr("domain");
	}
	
	public M setLogo(String logo) {
		set("logo", logo);
		return (M)this;
	}
	
	public String getLogo() {
		return getStr("logo");
	}
	
	public M setSubtitle(String subtitle) {
		set("subtitle", subtitle);
		return (M)this;
	}
	
	public String getSubtitle() {
		return getStr("subtitle");
	}
	
	public M setTitle(String title) {
		set("title", title);
		return (M)this;
	}
	
	public String getTitle() {
		return getStr("title");
	}
	
	public M setKeywords(String keywords) {
		set("keywords", keywords);
		return (M)this;
	}
	
	public String getKeywords() {
		return getStr("keywords");
	}
	
	public M setDescription(String description) {
		set("description", description);
		return (M)this;
	}
	
	public String getDescription() {
		return getStr("description");
	}
	
	public M setIcp(String icp) {
		set("icp", icp);
		return (M)this;
	}
	
	public String getIcp() {
		return getStr("icp");
	}
	
	public M setPolice(String police) {
		set("police", police);
		return (M)this;
	}
	
	public String getPolice() {
		return getStr("police");
	}
	
	public M setStatistical(String statistical) {
		set("statistical", statistical);
		return (M)this;
	}
	
	public String getStatistical() {
		return getStr("statistical");
	}
	
	public M setCopyright(String copyright) {
		set("copyright", copyright);
		return (M)this;
	}
	
	public String getCopyright() {
		return getStr("copyright");
	}
	
	public M setSiteId(Integer siteId) {
		set("siteId", siteId);
		return (M)this;
	}
	
	public Integer getSiteId() {
		return getInt("siteId");
	}
	
}

