package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminRole<M extends BaseAdminRole<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}
	
	public M setAdminId(Integer adminId) {
		set("adminId", adminId);
		return (M)this;
	}
	
	public Integer getAdminId() {
		return getInt("adminId");
	}
	
	public M setRoleId(Integer roleId) {
		set("roleId", roleId);
		return (M)this;
	}
	
	public Integer getRoleId() {
		return getInt("roleId");
	}
	
}

