package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSite<M extends BaseSite<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}
	
	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return getDate("createDate");
	}
	
	public M setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return getDate("updateDate");
	}
	
	public M setType(Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public Integer getType() {
		return getInt("type");
	}
	
	public M setProtocol(String protocol) {
		set("protocol", protocol);
		return (M)this;
	}
	
	public String getProtocol() {
		return getStr("protocol");
	}
	
	public M setPcTemplate(String pcTemplate) {
		set("pcTemplate", pcTemplate);
		return (M)this;
	}
	
	public String getPcTemplate() {
		return getStr("pcTemplate");
	}
	
	public M setIsMobile(Boolean isMobile) {
		set("isMobile", isMobile);
		return (M)this;
	}
	
	public Boolean getIsMobile() {
		return get("isMobile");
	}
	
	public M setMobileTemplate(String mobileTemplate) {
		set("mobileTemplate", mobileTemplate);
		return (M)this;
	}
	
	public String getMobileTemplate() {
		return getStr("mobileTemplate");
	}
	
	public M setIsDefault(Boolean isDefault) {
		set("isDefault", isDefault);
		return (M)this;
	}
	
	public Boolean getIsDefault() {
		return get("isDefault");
	}
	
	public M setName(String name) {
		set("name", name);
		return (M)this;
	}
	
	public String getName() {
		return getStr("name");
	}
	
	public M setCat(String cat) {
		set("cat", cat);
		return (M)this;
	}
	
	public String getCat() {
		return getStr("cat");
	}
	
	public M setDomain(String domain) {
		set("domain", domain);
		return (M)this;
	}
	
	public String getDomain() {
		return getStr("domain");
	}
	
}

