package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWechatMenu<M extends BaseWechatMenu<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}
	
	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return getDate("createDate");
	}
	
	public M setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return getDate("updateDate");
	}
	
	public M setParentId(Integer parentId) {
		set("parentId", parentId);
		return (M)this;
	}
	
	public Integer getParentId() {
		return getInt("parentId");
	}
	
	public M setSort(Integer sort) {
		set("sort", sort);
		return (M)this;
	}
	
	public Integer getSort() {
		return getInt("sort");
	}
	
	public M setName(String name) {
		set("name", name);
		return (M)this;
	}
	
	public String getName() {
		return getStr("name");
	}
	
	public M setType(String type) {
		set("type", type);
		return (M)this;
	}
	
	public String getType() {
		return getStr("type");
	}
	
	public M setKeywords(String keywords) {
		set("keywords", keywords);
		return (M)this;
	}
	
	public String getKeywords() {
		return getStr("keywords");
	}
	
	public M setUrl(String url) {
		set("url", url);
		return (M)this;
	}
	
	public String getUrl() {
		return getStr("url");
	}
	
	public M setMiniappid(String miniappid) {
		set("miniappid", miniappid);
		return (M)this;
	}
	
	public String getMiniappid() {
		return getStr("miniappid");
	}
	
	public M setMiniurl(String miniurl) {
		set("miniurl", miniurl);
		return (M)this;
	}
	
	public String getMiniurl() {
		return getStr("miniurl");
	}
	
	public M setMinipath(String minipath) {
		set("minipath", minipath);
		return (M)this;
	}
	
	public String getMinipath() {
		return getStr("minipath");
	}
	
}

