package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGuestbook<M extends BaseGuestbook<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}
	
	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return getDate("createDate");
	}
	
	public M setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return getDate("updateDate");
	}
	
	public M setContact(String contact) {
		set("contact", contact);
		return (M)this;
	}
	
	public String getContact() {
		return getStr("contact");
	}
	
	public M setMobile(String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public String getMobile() {
		return getStr("mobile");
	}
	
	public M setContent(String content) {
		set("content", content);
		return (M)this;
	}
	
	public String getContent() {
		return getStr("content");
	}
	
	public M setIp(String ip) {
		set("ip", ip);
		return (M)this;
	}
	
	public String getIp() {
		return getStr("ip");
	}
	
	public M setReplyContent(String replyContent) {
		set("replyContent", replyContent);
		return (M)this;
	}
	
	public String getReplyContent() {
		return getStr("replyContent");
	}
	
	public M setReplyDate(java.util.Date replyDate) {
		set("replyDate", replyDate);
		return (M)this;
	}
	
	public java.util.Date getReplyDate() {
		return getDate("replyDate");
	}
	
	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public Integer getStatus() {
		return getInt("status");
	}
	
	public M setSiteId(Integer siteId) {
		set("siteId", siteId);
		return (M)this;
	}
	
	public Integer getSiteId() {
		return getInt("siteId");
	}
	
}

