package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCompany<M extends BaseCompany<M>> extends Model<M> implements IBean {

	public M setId(Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public Integer getId() {
		return getInt("id");
	}
	
	public M setName(String name) {
		set("name", name);
		return (M)this;
	}
	
	public String getName() {
		return getStr("name");
	}
	
	public M setAddress(String address) {
		set("address", address);
		return (M)this;
	}
	
	public String getAddress() {
		return getStr("address");
	}
	
	public M setPostcode(String postcode) {
		set("postcode", postcode);
		return (M)this;
	}
	
	public String getPostcode() {
		return getStr("postcode");
	}
	
	public M setContact(String contact) {
		set("contact", contact);
		return (M)this;
	}
	
	public String getContact() {
		return getStr("contact");
	}
	
	public M setMobile(String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public String getMobile() {
		return getStr("mobile");
	}
	
	public M setPhone(String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public String getPhone() {
		return getStr("phone");
	}
	
	public M setFax(String fax) {
		set("fax", fax);
		return (M)this;
	}
	
	public String getFax() {
		return getStr("fax");
	}
	
	public M setEmail(String email) {
		set("email", email);
		return (M)this;
	}
	
	public String getEmail() {
		return getStr("email");
	}
	
	public M setQq(String qq) {
		set("qq", qq);
		return (M)this;
	}
	
	public String getQq() {
		return getStr("qq");
	}
	
	public M setWeixin(String weixin) {
		set("weixin", weixin);
		return (M)this;
	}
	
	public String getWeixin() {
		return getStr("weixin");
	}
	
	public M setH5(String h5) {
		set("h5", h5);
		return (M)this;
	}
	
	public String getH5() {
		return getStr("h5");
	}
	
	public M setApp(String app) {
		set("app", app);
		return (M)this;
	}
	
	public String getApp() {
		return getStr("app");
	}
	
	public M setBlicense(String blicense) {
		set("blicense", blicense);
		return (M)this;
	}
	
	public String getBlicense() {
		return getStr("blicense");
	}
	
	public M setOther(String other) {
		set("other", other);
		return (M)this;
	}
	
	public String getOther() {
		return getStr("other");
	}
	
	public M setSiteId(Integer siteId) {
		set("siteId", siteId);
		return (M)this;
	}
	
	public Integer getSiteId() {
		return getInt("siteId");
	}
	
}

