package com.cms.entity;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("cms_admin", "id", Admin.class);
		arp.addMapping("cms_admin_role", "id", AdminRole.class);
		arp.addMapping("cms_category", "id", Category.class);
		arp.addMapping("cms_company", "id", Company.class);
		arp.addMapping("cms_content", "id", Content.class);
		arp.addMapping("cms_div", "id", Div.class);
		arp.addMapping("cms_div_field", "id", DivField.class);
		arp.addMapping("cms_friend_link", "id", FriendLink.class);
		arp.addMapping("cms_guestbook", "id", Guestbook.class);
		arp.addMapping("cms_menu", "id", Menu.class);
		arp.addMapping("cms_model", "id", Model.class);
		arp.addMapping("cms_model_field", "id", ModelField.class);
		arp.addMapping("cms_nav", "id", Nav.class);
		arp.addMapping("cms_role", "id", Role.class);
		arp.addMapping("cms_role_site", "id", RoleSite.class);
		arp.addMapping("cms_setup", "id", Setup.class);
		arp.addMapping("cms_site", "id", Site.class);
		arp.addMapping("cms_slide", "id", Slide.class);
		arp.addMapping("cms_tag", "id", Tag.class);
		arp.addMapping("cms_web", "id", Web.class);
		arp.addMapping("cms_wechat_menu", "id", WechatMenu.class);
	}
}

